name: Vital
version: 1.0
main: io.github.caprapaul.vital.Vital
api-version: 1.14
commands:
  test:
    aliases: [test1, test2]
    description: This is a demo command.
    usage: /test
    permission: vital.test
    permission-message: You do not have permission to use this command!
  tpa:
    description: Send a teleport request to a player on the server.
    permission: vital.tpa
    permission-message: You do not have permission to use this command!
  tpahere:
    description: Send a teleport invite to a player on the server.
    permission: vital.tpa
    permission-message: You do not have permission to use this command!
  tpaccept:
    description: Accept a teleport request.
    permission: vital.tpaccept
    permission-message: You do not have permission to use this command!
  tpdeny:
    description: Deny a teleport request.
    permission: vital.tpdeny
    permission-message: You do not have permission to use this command!
  warp:
    description: Teleport to a warp.
    permission: vital.warp
    permission-message: You do not have permission to use this command!
  warps:
    description: Display available warp locations.
    permission: vital.warps
    permission-message: You do not have permission to use this command!
  setwarp:
    description: Set a warp location.
    permission: vital.setwarp
    permission-message: You do not have permission to use this command!
  delwarp:
    description: Delete a warp location.
    permission: vital.delwarp
    permission-message: You do not have permission to use this command!
  back:
    description: Teleport to the previous location.
    permission: vital.back
    permission-message: You do not have permission to use this command!
  heal:
    description: Sets health to full
    permission: vital.heal
    permission-message: You do not have permission to use this command!

permissions:
  vital.*:
    description: Gives access to all vital commands.
    children:
      vital.test: true
      vital.tpa: true
      vital.tpa.overridecooldown: true
      vital.tpahere: true
      vital.tpahere.overridecooldown: true
      vital.tpaccept: true
      vital.tpdeny: true
      vital.warp: true
      vital.warps: true
      vital.setwarp: true
      vital.delwarp: true
      vital.back: true
      vital.back.overridecooldown: true
      vital.heal: true
  vital.test:
    description: Allows you to use the /test command.
    default: true
  vital.tpa:
    description: Allows you to use the /tpa command.
    default: true
  vital.tpa.overridecooldown:
    description: Allows you to bypass /tpa cooldown.
    default: op
  vital.tpahere:
    description: Allows you to use the /tpahere command.
    default: true
  vital.tpahere.overridecooldown:
    description: Allows you to bypass /tpahere cooldown.
    default: op
  vital.tpaccept:
    description: Allows you to use the /tpaccept command.
    default: true
  vital.tpdeny:
    description: Allows you to use the /tpdeny command.
    default: true
  vital.warp:
    description: Allows you to use the /warp command.
    default: true
  vital.warps:
    description: Allows you to use the /warps command.
    default: true
  vital.setwarp:
    description: Allows you to use the /setwarp command.
    default: op
  vital.delwarp:
    description: Allows you to use the /delwarp command.
    default: op
  vital.back:
    description: Allows you to use the /back command.
    default: true
  vital.back.overridecooldown:
    description: Allows you to bypass /back cooldown.
    default: op
  vital.heal:
    description: Allows you to use the /heal command
    default: op
