name: Vital
version: 1.0
main: io.github.caprapaul.vital.Vital
api-version: 1.14
commands:
  test:
    aliases: [test1, test2]
    description: This is a demo command.
    usage: /test
    permission: vital.test
    permission-message: You do not have permission to use this command!
  tpa:
    description: Send a teleport request to a player on the server.
    permission: vital.tpa
    permission-message: You do not have permission to use this command!
  tpahere:
    description: Send a teleport invite to a player on the server.
    permission: vital.tpa
    permission-message: You do not have permission to use this command!
  tpaccept:
    description: Accept a teleport request.
    permission: vital.tpaccept
    permission-message: You do not have permission to use this command!
  tpdeny:
    description: Deny a teleport request.
    permission: vital.tpdeny
    permission-message: You do not have permission to use this command!
  warp:
    description: Teleport to a warp.
    permission: vital.warp
    permission-message: You do not have permission to use this command!
  warps:
    description: Display available warp locations.
    permission: vital.warps
    permission-message: You do not have permission to use this command!
  setwarp:
    description: Set a warp location.
    permission: vital.setwarp
    permission-message: You do not have permission to use this command!
  delwarp:
    description: Delete a warp location.
    permission: vital.delwarp
    permission-message: You do not have permission to use this command!
  home:
    description: Takes you to your default home, or a named home.
    permission: vital.home
    permission-message: You do not have permission to use this command!
  homes:
    description: Lists all your homes and their locations.
    permission: vital.homes
    permission-message: You do not have permission to use this command!
  sethome:
    description: Sets a home where you are currently are, also use this command to move a home.
    permission: vital.sethome
    permission-message: You do not have permission to use this command!
  delhome:
    description: Deletes your default home, or a named home.
    permission: vital.delhome
    permission-message: You do not have permission to use this command!

permissions:
  vital.*:
    description: Gives access to all vital commands.
    children:
      vital.test: true
      vital.tpa: true
      vital.tpahere: true
      vital.tpaccept: true
      vital.tpdeny: true
  vital.test:
    description: Allows you to use the /test command.
    default: true
  vital.tpa:
    description: Allows you to use the /tpa command.
    default: true
  vital.tpahere:
    description: Allows you to use the /tpahere command.
    default: true
  vital.tpaccept:
    description: Allows you to use the /tpaccept command.
    default: true
  vital.tpdeny:
    description: Allows you to use the /tpdeny command.
    default: true
  vital.warp:
    description: Allows you to use the /warp command.
    default: true
  vital.warps:
    description: Allows you to use the /warps command.
    default: true
  vital.setwarp:
    description: Allows you to use the /setwarp command.
    default: op
  vital.delwarp:
    description: Allows you to use the /delwarp command.
    default: op

  #Home commands
  vital.homes.*:
    description: Gives access to [home, homes, sethome, delhome] commands.
    children:
      vital.home: true
      vital.sethome: true
      vital.delhome: true
      vital.homes: true
  vital.home:
    description: Allows you to use the /home command.
    default: true
  vital.homes:
    description: Allows you to use the /homes command.
    default: op
  vital.sethome:
    description: Allows you to use the /sethome command.
    default: op
  vital.delhome:
    description: Allows you to use the /delhome command.
    default: op
