name: VitalChat
version: 1.0
main: io.github.caprapaul.vitalchat.VitalChat
api-version: 1.14
depend: [VitalCore]
commands:
  nick:
    description: Changes your nickname
    permission: vital.chat.nick
    permission-message: You do not have permission to use this command!
permissions:
  vital.chat.*:
    description: Gives access to all vital chat commands.
    children:
      vital.chat.nick: true
  vital.chat.nick:
    description: Allows you to use the /nick command.
    default: true
